<x-app-layout>
    <x-slot name="header"><div class="rounded-xl border border-amber-700/40 bg-amber-100 p-4 shadow-md"><h2 class="font-serif text-2xl font-bold text-amber-950">Editar idioma ou proficiência - {{ $character->name }}</h2></div></x-slot>
    <div class="min-h-screen bg-gradient-to-b from-[#b08a5a] to-[#6b4423] py-8"><div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8"><div class="rounded-2xl border-4 border-amber-900/60 bg-amber-100/90 p-6 text-amber-950 shadow-2xl sm:p-8">
        <form method="POST" action="{{ route('characters.language-proficiencies.update', [$character, $languageProficiency]) }}" class="space-y-4">@csrf @method('PUT')
            @if ($errors->any())<div class="rounded-lg border border-red-800/30 bg-red-100 p-4 text-red-900"><strong>Há erros no formulário:</strong><ul class="mt-2 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div><label class="block font-serif font-bold">Tipo</label><select name="type" required class="mt-1 w-full rounded-lg border-amber-800/40 bg-amber-50/70 focus:border-purple-800 focus:ring-purple-800"><option value="Idioma" @selected(old('type', $languageProficiency->type) === 'Idioma')>Idioma</option><option value="Proficiência" @selected(old('type', $languageProficiency->type) === 'Proficiência')>Proficiência</option></select></div>
            <div><label class="block font-serif font-bold">Nome</label><input type="text" name="name" value="{{ old('name', $languageProficiency->name) }}" required class="mt-1 w-full rounded-lg border-amber-800/40 bg-amber-50/70 focus:border-purple-800 focus:ring-purple-800"></div>
            <div><label class="block font-serif font-bold">Descrição</label><textarea name="description" rows="5" class="mt-1 w-full rounded-lg border-amber-800/40 bg-amber-50/70 focus:border-purple-800 focus:ring-purple-800">{{ old('description', $languageProficiency->description) }}</textarea></div>
            <div class="flex gap-2"><button class="rounded-lg border border-amber-900 bg-gradient-to-r from-amber-800 to-amber-950 px-4 py-2 font-semibold text-yellow-200">Atualizar</button><a href="{{ route('characters.language-proficiencies.index', $character) }}" class="rounded-lg border border-stone-600 bg-stone-300 px-4 py-2 font-semibold text-stone-900">Cancelar</a></div>
        </form>
    </div></div></div>
</x-app-layout>
