<x-app-layout>
    <x-slot name="header"><div class="rounded-xl border border-amber-700/40 bg-amber-100 p-5 shadow-md"><p class="font-serif text-xs uppercase tracking-[.3em] text-amber-800">Memórias da campanha</p><h2 class="font-serif text-3xl font-bold text-amber-950">Diário de sessão</h2></div></x-slot>
    <div class="min-h-screen bg-gradient-to-b from-[#b08a5a] to-[#6b4423] py-10"><div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-5 rounded-lg border border-green-800/30 bg-green-100 p-4 text-green-900 shadow">{{ session('success') }}</div>@endif
        <div class="mb-5 flex flex-wrap gap-2">@if($characters->contains(fn($character) => $character->canEdit(auth()->user())))<a href="{{ route('session-notes.create') }}" class="rounded-lg border border-amber-500/70 bg-gradient-to-r from-purple-950 to-indigo-950 px-5 py-3 font-serif font-bold text-amber-200 shadow">Nova anotação</a>@endif<a href="{{ route('dashboard') }}" class="rounded-lg border border-stone-600 bg-stone-300 px-5 py-3 font-serif font-bold text-stone-900">Voltar ao sumário</a></div>
        <div class="rounded-2xl border-4 border-amber-900/60 bg-amber-100/90 p-6 shadow-2xl">
            @forelse($notes as $note)<article class="mb-4 rounded-xl border border-amber-800/30 bg-amber-50/60 p-5 text-amber-950 shadow-sm"><div class="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-wide text-purple-900">{{ $note->character->name }}</p><h3 class="font-serif text-2xl font-bold">{{ $note->title }}</h3><p class="mt-1 text-xs text-amber-900/60">{{ $note->session_date?->format('d/m/Y') ?? 'Data não informada' }} · por {{ $note->author?->name ?? 'Usuário removido' }}</p></div>@if($note->canEdit(auth()->user()))<div class="flex gap-2"><a href="{{ route('session-notes.edit', $note) }}" class="font-bold text-amber-800 hover:underline">Editar</a><form method="POST" action="{{ route('session-notes.destroy', $note) }}" onsubmit="return confirm('Excluir esta anotação?')">@csrf @method('DELETE')<button class="font-bold text-red-800 hover:underline">Excluir</button></form></div>@endif</div><p class="mt-4 whitespace-pre-line leading-relaxed text-amber-950/80">{{ $note->content }}</p></article>
            @empty<div class="rounded-xl border border-dashed border-amber-800/35 p-10 text-center text-amber-950"><h3 class="font-serif text-2xl font-bold">Nenhuma memória registrada</h3><p class="mt-2">Crie a primeira anotação para uma ficha que você possa editar.</p></div>@endforelse
        </div>
    </div></div>
</x-app-layout>
